### ISSUE TITLE
Confusing state of asset creation

### ISSUE THREAD

**Issue by leonidr-da** [digital-asset/daml-ui-template#18]
@gaborh-da Was there further work to be done for https://github.com/digital-asset/daml-ui-template/pull/13 to limit Asset creation?

At the moment there are two ways to create an asset, create it or exercise on the AssetCreatorRole. But from the UI perspective I can see 2 inconsistencies:

1. the New Asset page doesn't work; we can't use empty strings for `dateOfIssuance` and `value`. Should we remove this page entirely?
2. Users aren't automatically granted the `AssetCreaterRole`, only `Alice` so they can't test it out.

**Comment by gaborh-da** [comment]
There was further work to be done but I am working on another, urgent project at the moment, please go on with the suggested solution.

**Comment by GeorgSchneider** [comment]
I've merged https://github.com/digital-asset/daml-ui-template/pull/19 in now
