### ISSUE TITLE
Current state of master is unstable

### ISSUE THREAD

**Issue by adam-rocska** [digital-asset/daml-ui-template#30]
I git cloned the current state `89e2aa993ca9006ffbdb184f35da16dd27619dcc` and though it builds, and yarn starts the gui, it renders, but doesn't practically work when for instance I try to create a new asset.

The error from the console:
```
[Error] Failed to load resource: the server responded with a status of 401 (Unauthorized) (create, line 0)
[Log] {errors: ["JwtDecoder.Error: 'decode, The token was expected to have 3 parts, but got 1."], status: 401} (0.chunk.js, line 1228)
[Error] Unhandled Promise Rejection: [object Object]
	(névtelen függvény) (main.chunk.js:1701)
	asyncFunctionResume
	(névtelen függvény)
	promiseReactionJobWithoutPromise
	promiseReactionJob
```

**Comment by adam-rocska** [comment]
@rlegmann : FYI

**Comment by leonidr-da** [comment]
I wasn't able to reproduce this with 1.2 or 1.5. Did you by any chance have different versions (ex 1.5) between the server and web client (ex 1.2)? There was a similar issue that could have been triggered between incompatible versions previously.

**Comment by adam-rocska** [comment]
Yup. Versionmismatch. Solved ✌️👍
